### ISSUE TITLE
Integrate Weather API

### ISSUE THREAD

**Issue by M4TThys123** [M4TThys123/WeatherAppPlus#2]
#### Description
Integrate a weather API (e.g., OpenWeatherMap) to fetch weather data for the application.
#### Tasks
- [x] Set up API key for weather data fetching
 `d45c14881afb57e1425ff32ace6410a3`
- [x] Intergrate a functions to fetch current weather 
- [x] Intergrate a functions to fetch 48h forecast.
- [ ] Intergrate a functions to fetch  5-day forecast data
- [x] Handle API responses and errors gracefully in the application
- [ ] Make a networkoffline component
